#!/usr/bin/env python3
"""
复杂用例测试 - 构建一个完整的 Flask TODO API

这个测试会创建一个多文件的项目：
1. models.py - 数据模型
2. api.py - Flask API endpoints
3. utils.py - 辅助函数
4. test_api.py - 单元测试
"""

import sys
import os
import subprocess
import tempfile

sys.path.insert(0, os.path.dirname(__file__))
from coding_agent_api import CodingAgentAPI, execute_tasks


def setup_project():
    """创建测试项目"""
    project_dir = tempfile.mkdtemp(prefix="flask-todo-")
    
    print(f"📁 Creating project: {project_dir}")
    
    # 初始化 git
    subprocess.run(["git", "init"], cwd=project_dir, capture_output=True)
    subprocess.run(["git", "config", "user.email", "test@test.com"], cwd=project_dir, capture_output=True)
    subprocess.run(["git", "config", "user.name", "Test"], cwd=project_dir, capture_output=True)
    
    # 创建 README
    readme = os.path.join(project_dir, "README.md")
    with open(readme, 'w') as f:
        f.write("# Flask TODO API\n\nAutomatically generated by Coding Agent\n")
    
    subprocess.run(["git", "add", "README.md"], cwd=project_dir, capture_output=True)
    subprocess.run(["git", "commit", "-m", "Initial commit"], cwd=project_dir, capture_output=True)
    
    return project_dir


def test_complex_project():
    """测试复杂项目"""
    
    print("🚀 Complex Use Case: Flask TODO API")
    print("=" * 60)
    
    # 设置项目
    project_dir = setup_project()
    print(f"✅ Project initialized at: {project_dir}")
    print()
    
    # 定义任务序列
    tasks = [
        # Task 1: 数据模型
        """Create models.py with a Todo class that has:
        - id (int)
        - title (string)
        - completed (boolean)
        - created_at (datetime)
        Include a to_dict() method""",
        
        # Task 2: Flask API
        """Create api.py with Flask REST API:
        - GET /todos - list all todos
        - POST /todos - create new todo
        - PUT /todos/<id> - update todo
        - DELETE /todos/<id> - delete todo
        Use in-memory storage (list)""",
        
        # Task 3: 辅助函数
        """Create utils.py with helper functions:
        - validate_todo(data) - validate todo data
        - format_response(data, status) - format JSON response""",
    ]
    
    # 执行所有任务
    print(f"📝 Executing {len(tasks)} tasks...")
    print()
    
    results = execute_tasks(
        tasks=tasks,
        workdir=project_dir,
        debug=True,
        timeout=300  # 每个任务最多5分钟
    )
    
    # 统计结果
    print("\n" + "=" * 60)
    print("📊 FINAL RESULTS")
    print("=" * 60)
    
    total_duration = sum(r.duration for r in results)
    total_confirms = sum(r.auto_confirms for r in results)
    total_files = sum(len(r.files_created) for r in results)
    
    print(f"\n✅ Completed: {len([r for r in results if r.success])}/{len(tasks)} tasks")
    print(f"⏱️  Total duration: {total_duration:.1f}s")
    print(f"🔄 Total auto-confirms: {total_confirms}")
    print(f"📄 Total files created: {total_files}")
    
    # 列出所有创建的文件
    print(f"\n📂 Project structure:")
    for result in results:
        for filename in result.files_created:
            filepath = os.path.join(project_dir, filename)
            if os.path.exists(filepath):
                size = os.path.getsize(filepath)
                print(f"  ✅ {filename} ({size} bytes)")
    
    # 显示文件内容
    print(f"\n📄 File contents:")
    for result in results:
        for filename in result.files_created:
            filepath = os.path.join(project_dir, filename)
            if os.path.exists(filepath):
                print(f"\n{'-' * 60}")
                print(f"FILE: {filename}")
                print('-' * 60)
                with open(filepath, 'r') as f:
                    content = f.read()
                    # 只显示前30行
                    lines = content.split('\n')
                    if len(lines) > 30:
                        print('\n'.join(lines[:30]))
                        print(f"\n... ({len(lines) - 30} more lines)")
                    else:
                        print(content)
    
    print(f"\n{'=' * 60}")
    print(f"💡 Project preserved at: {project_dir}")
    print(f"{'=' * 60}")
    
    # 返回结果
    return {
        'success': all(r.success for r in results),
        'project_dir': project_dir,
        'results': results,
        'total_duration': total_duration,
        'total_files': total_files,
    }


if __name__ == "__main__":
    result = test_complex_project()
    
    if result['success']:
        print("\n✅ All tasks completed successfully!")
        sys.exit(0)
    else:
        print("\n❌ Some tasks failed")
        sys.exit(1)
