/**
 * CAM Desktop — embedded CAM Hub (CAM-DESK-DIRECT-010..019,
 * CAM-DESK-HUB-010..012).
 *
 * Implements the Direct connection target as a self-contained Node
 * HTTP server inside Electron main. NO host CAM runtime is required:
 * no `cam` CLI, no `python`, no WSL, no shell spawn. Everything is
 * stdlib (`http`, `crypto`, `fs`, `path`).
 *
 * Wire contract: a strict subset of the existing CAM API that the
 * renderer (`web/js/api.js`) already speaks. Endpoints implemented in
 * this first pass:
 *
 *   GET  /api/system/health       — CAM-shaped readiness, no auth
 *   GET  /api/system/config       — minimal config view, bearer auth
 *   GET  /api/contexts            — list contexts from app-data store
 *   GET  /api/contexts/:name      — 404 in this pass (registry empty)
 *   GET  /api/agents              — list agents from app-data store
 *   GET  /api/agents/:id          — 404 in this pass (registry empty)
 *   GET  /api/agents/:id/output?lines=N&format=ansi|plain — tail capture
 *   GET  /api/agents/:id/fulloutput?format=ansi|plain      — full scrollback
 *   GET  /api/agents/:id/logs     — empty logs shape
 *
 * Mutating endpoints (POST /api/agents, PATCH /api/agents/:id,
 * DELETE /api/agents/:id, /restart, and context-copy cleanup paths
 * still return 501 Not Implemented with a JSON error
 * body so the renderer can surface it cleanly. They will be wired in
 * a later pass that pins down DIRECT-015..018 (node management +
 * credential references) and a remote-controller transport.
 *
 * WebSocket (`/api/ws`) is intentionally omitted in this pass:
 * `CamApi._connectEventStream()` tolerates ws failure and the
 * renderer falls back to its existing 5s REST polling.
 *
 * Storage: a single JSON file at `<userData>/embedded-hub.json` with
 *   { version: 1, contexts: [], agents: [], adapters: [...] }
 * Loaded on first start and rewritten only when the registry grows.
 *
 * Auth: every /api/* endpoint except /api/system/health requires
 * `Authorization: Bearer <token>` where token is generated by
 * `crypto.randomBytes(24).toString('base64url')` on each Start.
 *
 * Lifecycle: a single owned server at 127.0.0.1:8420 (or first free
 * port in 8420..8429). Stop closes the server; restart = stop+start.
 * The main process is the only thing that can lifecycle this — the
 * renderer-facing surface lives in `preload.cjs` as
 * `CamBridge.directHub.*`.
 */

'use strict';

const http   = require('node:http');
const crypto = require('node:crypto');
const fs     = require('node:fs');
const os     = require('node:os');
const path   = require('node:path');

const DEFAULT_PORT       = 8420;
const PORT_SCAN_RANGE    = 10;
const LOG_BUFFER_LINES   = 200;
const DEFAULT_ADAPTERS   = ['claude', 'codex', 'cursor'];
const STORE_VERSION      = 1;
const HUB_PRODUCT_VERSION = 'cam-desktop-embedded-1';

/* ─────────────── State ─────────────── */

const state = {
  server:     null,
  port:       null,
  token:      null,
  startedAt:  0,
  owned:      false,
  logs:       [],   // ring buffer of recent events {kind,text,ts}
  lastError:  null,
  store:      null, // loaded JSON store
  dataDir:    null,
  storePath:  null,
};

function tokenFingerprint(tok) {
  if (!tok || typeof tok !== 'string') return null;
  return 'sha256:' + crypto.createHash('sha256').update(tok).digest('hex').slice(0, 24);
}

function genToken() {
  return crypto.randomBytes(24).toString('base64url');
}

function pushLog(kind, text) {
  const line = { kind, text: String(text || ''), ts: Date.now() };
  state.logs.push(line);
  if (state.logs.length > LOG_BUFFER_LINES) {
    state.logs.splice(0, state.logs.length - LOG_BUFFER_LINES);
  }
}

/* ─────────────── App-data store ─────────────── */

function _emptyStore() {
  return {
    version:  STORE_VERSION,
    contexts: [],
    agents:   [],
    adapters: DEFAULT_ADAPTERS.slice(),
  };
}

function loadStore(dataDir) {
  state.dataDir = dataDir;
  state.storePath = path.join(dataDir, 'embedded-hub.json');
  try {
    fs.mkdirSync(dataDir, { recursive: true });
  } catch (e) { pushLog('warn', `mkdir userData failed: ${e.message}`); }

  try {
    const raw = fs.readFileSync(state.storePath, 'utf8');
    const parsed = JSON.parse(raw);
    state.store = {
      ..._emptyStore(),
      ...parsed,
      adapters: Array.isArray(parsed.adapters) && parsed.adapters.length
        ? parsed.adapters
        : DEFAULT_ADAPTERS.slice(),
    };
    _repairStoreAgents();
  } catch (e) {
    if (e.code !== 'ENOENT') pushLog('warn', `store read failed: ${e.message}`);
    state.store = _emptyStore();
    try { fs.writeFileSync(state.storePath, JSON.stringify(state.store, null, 2)); }
    catch (e2) { pushLog('warn', `store init write failed: ${e2.message}`); }
  }
}

/** Atomically write the JSON store: write to a sibling .tmp file
 *  first, then rename. The rename is effectively atomic on POSIX
 *  and on Windows when the destination exists. */
function saveStore() {
  if (!state.storePath || !state.store) return;
  const tmp = state.storePath + '.tmp';
  try {
    fs.writeFileSync(tmp, JSON.stringify(state.store, null, 2));
    fs.renameSync(tmp, state.storePath);
  } catch (e) {
    pushLog('warn', `store write failed: ${e.message}`);
  }
}

function _agentDedupeKey(a) {
  if (!a || !a.id) return '';
  const type = a.machine_type || a.transport_type || 'local';
  const host = a.machine_host || '';
  const user = a.machine_user || '';
  const port = a.machine_port == null ? '' : String(a.machine_port);
  // Local records do not carry a meaningful remote endpoint; keep their
  // context in the key. SSH imports are deduped by endpoint+agent id so
  // stale rows imported under old remote context names are collapsed.
  const ctx = type === 'ssh' ? '' : (a.context_name || '');
  return `${type}|${user}|${host}|${port}|${ctx}|${a.id}`;
}

function _contextForAgentRecord(a) {
  const ctxs = (state.store && Array.isArray(state.store.contexts)) ? state.store.contexts : [];
  if (!a || !ctxs.length) return null;
  const byName = a.context_name ? ctxs.find(c => c && c.name === a.context_name) : null;
  if (byName) return byName;
  return ctxs.find((ctx) => {
    const m = (ctx && ctx.machine) || {};
    return (m.type || 'local') === (a.machine_type || a.transport_type || 'local')
      && (m.host || '') === (a.machine_host || '')
      && (m.user || '') === (a.machine_user || '')
      && String(m.port == null ? '' : m.port) === String(a.machine_port == null ? '' : a.machine_port);
  }) || null;
}

function _repairStoreAgents() {
  if (!state.store || !Array.isArray(state.store.agents)) return false;
  const out = [];
  const byKey = new Map();
  let changed = false;

  for (const raw of state.store.agents) {
    if (!raw || typeof raw !== 'object' || !raw.id) {
      out.push(raw);
      continue;
    }
    const ctx = _contextForAgentRecord(raw);
    let a = raw;
    if (ctx && raw.context_name !== ctx.name) {
      a = { ...raw };
      if (!a.remote_context_name && raw.context_name) a.remote_context_name = raw.context_name;
      a.context_name = ctx.name;
      if (!a.context_id && ctx.id) a.context_id = ctx.id;
      changed = true;
    }
    const key = _agentDedupeKey(a);
    if (!key) {
      out.push(a);
      continue;
    }
    const prior = byKey.get(key);
    if (prior != null) {
      out[prior] = a;
      changed = true;
    } else {
      byKey.set(key, out.length);
      out.push(a);
    }
  }

  if (changed) {
    const before = state.store.agents.length;
    state.store.agents = out;
    saveStore();
    pushLog('info', `agent registry repaired: ${before} -> ${out.length}`);
  }
  return changed;
}

/* ─────────────── HTTP helpers ─────────────── */

/** CORS headers for loopback-only Electron renderer.
 *
 * The renderer loads from a `file://` URL but `fetch()`es
 * `http://127.0.0.1:<port>/api/...` with an Authorization header.
 * Chromium treats that as a cross-origin request and emits an OPTIONS
 * preflight, so every response needs explicit CORS headers and OPTIONS
 * must answer 204. The Hub only ever binds to 127.0.0.1, so allowing
 * `*` here is acceptable: the socket itself is unreachable from
 * outside the host.
 */
function corsHeaders() {
  return {
    'Access-Control-Allow-Origin':  '*',
    'Access-Control-Allow-Headers': 'Authorization, Content-Type',
    'Access-Control-Allow-Methods': 'GET, POST, PUT, PATCH, DELETE, OPTIONS',
    'Access-Control-Max-Age':       '600',
    'Vary':                         'Origin',
  };
}

function sendJson(res, status, body) {
  const buf = Buffer.from(JSON.stringify(body), 'utf8');
  res.writeHead(status, {
    'Content-Type':   'application/json; charset=utf-8',
    'Content-Length': buf.length,
    'Cache-Control':  'no-store',
    ...corsHeaders(),
  });
  res.end(buf);
}

function send501(res, what) {
  sendJson(res, 501, {
    error:           'not_implemented',
    detail:          what,
    embedded_hub:    true,
    next_stage_req:  'CAM-DESK-DIRECT-015..018',
  });
}

function send404(res) {
  sendJson(res, 404, { error: 'not_found' });
}

function send400(res, detail, code) {
  // Default `error` code is `bad_request`; callers can pass a more
  // specific code (e.g. `safe_storage_unavailable`, `invalid_name`)
  // so renderers can switch on it instead of grepping `detail`.
  sendJson(res, 400, { error: code || 'bad_request', detail });
}

const REQ_BODY_MAX = 25 * 1024 * 1024; // upload payloads are base64 JSON

function readJsonBody(req) {
  return new Promise((resolve, reject) => {
    let size = 0;
    const chunks = [];
    req.on('data', (chunk) => {
      size += chunk.length;
      if (size > REQ_BODY_MAX) {
        reject(new Error('body_too_large'));
        try { req.destroy(); } catch {}
        return;
      }
      chunks.push(chunk);
    });
    req.on('end', () => {
      const text = Buffer.concat(chunks).toString('utf8');
      if (!text) return resolve({});
      try { resolve(JSON.parse(text)); }
      catch { reject(new Error('invalid_json')); }
    });
    req.on('error', reject);
  });
}

/* ─────────────── Context helpers (CAM-DESK-DIRECT-014..018) ─────────────── */

const NAME_RE      = /^[A-Za-z0-9_-]{1,64}$/;
const AUTH_METHODS = new Set(['key', 'password', 'agent']);

function nowIso() { return new Date().toISOString(); }

// Optional credential store injected by Electron main. The Node smoke
// can install a deterministic stub; the hub itself is unaware of the
// implementation. Absent → no Remember support (Remember=true with no
// store returns 400 below; non-Remember create works fine).
let _credentialStore = null;

// Optional SSH transport injected by Electron main (CAM-DESK-DIRECT-019).
// Same idea: hub is unaware of the implementation. The Node smoke
// installs a deterministic stub; in Electron main this is
// `ssh-transport.cjs` wrapping ssh2.
let _sshTransport = null;

// Remote agent-discovery command. Two-pass: prefer the embedded camc
// shim, fall back to the system `camc` on PATH (which is what the
// unified CAM/camc environment installs).
const SYNC_DEFAULT_TIMEOUT_MS = 15000;
const REMOTE_CAMC = '~/.cam/camc';
const REMOTE_CAMC_UPLOAD_PATH = '.cam/camc.tmp';

function configure({ credentialStore, sshTransport } = {}) {
  if (credentialStore !== undefined) _credentialStore = credentialStore || null;
  if (sshTransport    !== undefined) _sshTransport    = sshTransport    || null;
}

function _credentialAvailable() {
  return !!(_credentialStore && typeof _credentialStore.available === 'function' && _credentialStore.available());
}

function _normalizeAuthMethod(body, keyFile) {
  let m = body.auth_method == null ? '' : String(body.auth_method).trim().toLowerCase();
  if (!m) {
    // Reasonable default: if a key_file was supplied, assume 'key';
    // otherwise 'agent' (use ssh-agent / default key search).
    m = keyFile ? 'key' : 'agent';
  }
  if (!AUTH_METHODS.has(m)) return null;
  return m;
}

/** Helper: persist a single remembered secret for `(contextId, kind)`
 *  via the injected credential store. Returns { ok } or
 *  { error, detail }. Refuses to save when Remember was asked for
 *  but the store / safeStorage are unavailable — we never fall back
 *  to plaintext. */
function _saveRememberedSecret(contextId, kind, secret) {
  if (!_credentialStore || typeof _credentialStore.put !== 'function') {
    return { error: 'credential_store_unavailable', detail: 'Remember requires the Electron credential store.' };
  }
  if (!_credentialAvailable()) {
    return { error: 'safe_storage_unavailable', detail: 'OS keychain/safeStorage is not available; cannot remember secrets.' };
  }
  const res = _credentialStore.put(`${contextId}:${kind}`, kind, secret);
  if (!res || res.ok !== true) {
    return { error: res && res.error ? res.error : 'credential_save_failed' };
  }
  return { ok: true, ref: res.ref, kind, saved_at: res.saved_at };
}

function _cascadeDeleteCreds(contextId) {
  if (!_credentialStore || typeof _credentialStore.removeForContext !== 'function') return;
  try { _credentialStore.removeForContext(contextId); }
  catch (_) {}
}

function buildContextRecord(body) {
  const name = String(body.name || '').trim();
  if (!NAME_RE.test(name)) {
    return { error: 'invalid_name', detail: 'name must match [A-Za-z0-9_-]{1,64}' };
  }
  const ctxPath = String(body.path || '').trim();
  if (!ctxPath) {
    return { error: 'missing_path', detail: 'path is required' };
  }
  const host = body.host == null ? '' : String(body.host).trim();
  const user = body.user == null ? '' : String(body.user).trim();
  const port = body.port == null || body.port === ''
    ? null
    : Number.parseInt(body.port, 10);
  if (port != null && (!Number.isFinite(port) || port < 1 || port > 65535)) {
    return { error: 'invalid_port', detail: 'port must be 1..65535' };
  }
  const isSSH = !!host;
  if (isSSH && !user) {
    return { error: 'missing_user', detail: 'SSH contexts require host and user' };
  }
  const keyFile  = body.key_file  == null ? '' : String(body.key_file).trim();
  const envSetup = body.env_setup == null ? '' : String(body.env_setup).trim();
  const tags     = Array.isArray(body.tags)
    ? body.tags.filter(t => typeof t === 'string' && t).slice(0, 32)
    : [];

  const authMethod = isSSH ? _normalizeAuthMethod(body, keyFile) : null;
  if (isSSH && !authMethod) {
    return { error: 'invalid_auth_method', detail: 'auth_method must be one of: key, password, agent' };
  }

  // CAM-DESK-DIRECT-018 enforcement: a password-auth context with no
  // usable credential would be silently unsyncable. The Hub allows
  // exactly two valid shapes:
  //   1. remember_password=true (the normal GUI path; the password
  //      is persisted via safeStorage and the context owns its own
  //      credential).
  //   2. allow_one_shot=true (the source-CLI debug path; the
  //      context is created with credential_saved=false and the
  //      caller must pass `password` on every POST /sync. Useful
  //      when Electron safeStorage isn't available, e.g. the dev
  //      `camui` CLI.)
  // Anything else (auth_method=password with no remember and no
  // allow_one_shot) is refused at create time.
  const allowOneShot = !!body.allow_one_shot;
  if (isSSH && authMethod === 'password'
      && !body.remember_password && !allowOneShot) {
    return {
      error:  'missing_credential',
      detail: 'auth_method=password requires remember_password=true (GUI path) OR allow_one_shot=true (CLI debug path). The Hub will not create a context that has no way to authenticate.',
    };
  }

  const id = crypto.randomUUID();
  const machine = {
    type:       isSSH ? 'ssh' : 'local',
    host:       isSSH ? host : '',
    user:       isSSH ? user : '',
    port:       isSSH ? (port || 22) : null,
    key_file:   isSSH && authMethod === 'key' ? keyFile : '',
    env_setup:  envSetup,
  };
  if (isSSH) {
    machine.auth_method      = authMethod;       // 'key' | 'password' | 'agent'
    machine.credential_ref   = '';               // populated below if remembered
    machine.credential_kind  = '';               // 'password' | 'passphrase'
    machine.credential_saved = false;
    // Source-CLI debug marker: when true, the context was created
    // without a stored credential and Sync requires a one-shot
    // `password` (or `passphrase`) in the body. Useful for
    // safeStorage-less debug.
    if (allowOneShot) machine.allow_one_shot = true;
  }

  // Optional Remember support. Raw secret never makes it to the
  // record we return / persist — it goes to the credential store
  // (encrypted via safeStorage) and we only carry the ref/metadata.
  if (isSSH) {
    if (authMethod === 'password' && body.remember_password) {
      const secret = body.password == null ? '' : String(body.password);
      if (!secret) {
        return { error: 'missing_password', detail: 'remember_password=true requires a non-empty password' };
      }
      const saved = _saveRememberedSecret(id, 'password', secret);
      if (saved.error) return saved;
      machine.credential_ref   = saved.ref;
      machine.credential_kind  = 'password';
      machine.credential_saved = true;
    }
    if (authMethod === 'key' && body.remember_passphrase) {
      const secret = body.passphrase == null ? '' : String(body.passphrase);
      if (!secret) {
        return { error: 'missing_passphrase', detail: 'remember_passphrase=true requires a non-empty passphrase' };
      }
      const saved = _saveRememberedSecret(id, 'passphrase', secret);
      if (saved.error) return saved;
      machine.credential_ref   = saved.ref;
      machine.credential_kind  = 'passphrase';
      machine.credential_saved = true;
    }
  }

  return {
    record: {
      id,
      name,
      path:         ctxPath,
      machine,
      tags,
      created_at:   nowIso(),
      last_used_at: null,
    },
  };
}

function findContextByName(name) {
  if (!state.store) return null;
  return state.store.contexts.find(c => c.name === name) || null;
}

function applyContextUpdate(existing, body) {
  // Apply only known scalar fields; refuse to rewrite id/created_at.
  const next = { ...existing };
  if (body.path != null)       next.path = String(body.path).trim();
  if (body.tags != null && Array.isArray(body.tags)) {
    next.tags = body.tags.filter(t => typeof t === 'string' && t).slice(0, 32);
  }
  const m = { ...(existing.machine || {}) };
  if (body.host      != null) m.host      = String(body.host).trim();
  if (body.user      != null) m.user      = String(body.user).trim();
  if (body.key_file  != null) m.key_file  = String(body.key_file).trim();
  if (body.env_setup != null) m.env_setup = String(body.env_setup).trim();
  if (body.port      != null && body.port !== '') {
    const p = Number.parseInt(body.port, 10);
    if (!Number.isFinite(p) || p < 1 || p > 65535) {
      return { error: 'invalid_port', detail: 'port must be 1..65535' };
    }
    m.port = p;
  }
  m.type = m.host ? 'ssh' : 'local';
  if (m.type === 'ssh' && !m.user) {
    return { error: 'missing_user', detail: 'SSH contexts require host and user' };
  }

  // Auth method change tracking: when auth_method changes, drop the
  // previous credential ref. The new method's secret (if any) is
  // saved further below.
  let prevMethod = m.auth_method || '';
  let nextMethod = prevMethod;
  if (m.type === 'ssh') {
    if (body.auth_method != null) {
      const normalized = _normalizeAuthMethod({ auth_method: body.auth_method }, m.key_file);
      if (!normalized) {
        return { error: 'invalid_auth_method', detail: 'auth_method must be one of: key, password, agent' };
      }
      nextMethod = normalized;
    }
    if (!nextMethod) nextMethod = m.key_file ? 'key' : 'agent';
    if (nextMethod !== prevMethod) {
      _cascadeDeleteCreds(existing.id);
      m.credential_ref   = '';
      m.credential_kind  = '';
      m.credential_saved = false;
    }
    m.auth_method = nextMethod;
    // key_file only makes sense for the 'key' method.
    if (nextMethod !== 'key') m.key_file = '';
    // Same DIRECT-018 enforcement as create: a password-auth
    // context must either persist a credential now, already have
    // one, OR be explicitly marked as one-shot (CLI debug). Refuse
    // any other shape so we never silently end up with an
    // unsyncable record.
    if (nextMethod === 'password'
        && !body.remember_password
        && !m.credential_saved
        && !m.allow_one_shot
        && !body.allow_one_shot) {
      return {
        error:  'missing_credential',
        detail: 'auth_method=password requires remember_password=true OR allow_one_shot=true.',
      };
    }
    if (body.allow_one_shot === true) m.allow_one_shot = true;
  } else {
    delete m.auth_method;
    delete m.credential_ref;
    delete m.credential_kind;
    delete m.credential_saved;
  }

  // Optional Remember updates. Raw secrets never land in the record.
  if (m.type === 'ssh') {
    if (nextMethod === 'password' && body.remember_password) {
      const secret = body.password == null ? '' : String(body.password);
      if (!secret) {
        return { error: 'missing_password', detail: 'remember_password=true requires a non-empty password' };
      }
      const saved = _saveRememberedSecret(existing.id, 'password', secret);
      if (saved.error) return saved;
      m.credential_ref   = saved.ref;
      m.credential_kind  = 'password';
      m.credential_saved = true;
    } else if (nextMethod === 'key' && body.remember_passphrase) {
      const secret = body.passphrase == null ? '' : String(body.passphrase);
      if (!secret) {
        return { error: 'missing_passphrase', detail: 'remember_passphrase=true requires a non-empty passphrase' };
      }
      const saved = _saveRememberedSecret(existing.id, 'passphrase', secret);
      if (saved.error) return saved;
      m.credential_ref   = saved.ref;
      m.credential_kind  = 'passphrase';
      m.credential_saved = true;
    } else if (body.forget_credential === true) {
      _cascadeDeleteCreds(existing.id);
      m.credential_ref   = '';
      m.credential_kind  = '';
      m.credential_saved = false;
    }
  }

  next.machine = m;
  return { record: next };
}

/* ─────────────── Remote sync (CAM-DESK-DIRECT-016/019) ─────────────── */

/** Fetch the decrypted credential secret for a context, if any.
 *  Returns the string or null. Main-process only — never leaves
 *  this file. */
function _credentialFor(ctx) {
  if (!ctx || !ctx.machine) return null;
  const ref = ctx.machine.credential_ref;
  if (!ref || !_credentialStore || typeof _credentialStore.get !== 'function') return null;
  try { return _credentialStore.get(ref); } catch (_) { return null; }
}

/** Normalize one record from `camc --json list` into the field shape
 *  Desktop renderer expects (web/js/desktop/shell.js +
 *  web/js/desktop/nodes-mode.js). camc emits a nested `task` object;
 *  we hoist `task.name → task_name`, `task.tool → tool`, etc., and
 *  stamp machine_host/user/port/type from the originating context so
 *  Nodes mode can group correctly. */
function _normalizeAgent(rec, ctx) {
  if (!rec || typeof rec !== 'object') return null;
  const t = (rec.task && typeof rec.task === 'object') ? rec.task : {};
  const m = (ctx && ctx.machine) || {};
  return {
    // Identity
    id:             String(rec.id || ''),
    session_id:     rec.session_id || '',
    // Task surface — flatten what shell.js / start-agent-mode read.
    task_name:      String(t.name || ''),
    tool:           String(t.tool || rec.tool || ''),
    prompt:         t.prompt || '',
    auto_confirm:   !!t.auto_confirm,
    auto_exit:      !!t.auto_exit,
    tags:           Array.isArray(t.tags) ? t.tags.slice(0, 32) : (Array.isArray(rec.tags) ? rec.tags.slice(0, 32) : []),
    // Context linkage — keep both names that downstream code uses.
    // Force `context_name` to the LOCAL ctx.name so duplicate sync
    // doesn't strand records under whatever stale value the remote
    // camc happened to report (ours vs theirs may diverge across
    // machines). Preserve the remote value separately for diagnostics.
    context_id:          rec.context_id || '',
    context_name:        (ctx && ctx.name) || '',
    remote_context_name: rec.context_name || '',
    context_path:        rec.context_path || rec.path || '',
    path:           rec.context_path || rec.path || '',
    transport_type: rec.transport_type || (m.type || 'local'),
    // Lifecycle.
    status:         rec.status || 'unknown',
    state:          rec.state  || '',
    tmux_session:   rec.tmux_session || rec.session || '',
    session:        rec.tmux_session || rec.session || '',
    tmux_socket:    rec.tmux_socket || '',
    pid:            rec.pid || null,
    hostname:       rec.hostname || '',
    created_at:      rec.created_at || t.created_at || null,
    updated_at:      rec.updated_at || t.updated_at || rec.last_active_at || t.last_active_at || rec.last_seen_at || t.last_seen_at || rec.activity_at || t.activity_at || rec.modified_at || t.modified_at || rec.mtime || t.mtime || null,
    last_active_at:  rec.last_active_at || t.last_active_at || null,
    last_seen_at:    rec.last_seen_at || t.last_seen_at || null,
    activity_at:     rec.activity_at || t.activity_at || null,
    modified_at:     rec.modified_at || t.modified_at || null,
    mtime:           rec.mtime || t.mtime || null,
    started_at:      rec.started_at || t.started_at || null,
    completed_at:    rec.completed_at || t.completed_at || null,
    exit_reason:     rec.exit_reason  || null,
    retry_count:    rec.retry_count  || 0,
    cost_estimate:  rec.cost_estimate || null,
    files_changed:  Array.isArray(rec.files_changed) ? rec.files_changed : [],
    // Stamp the originating node so Nodes-mode can group + filter.
    machine_host:   m.host || '',
    machine_user:   m.user || '',
    machine_port:   m.port || null,
    machine_type:   m.type || 'local',
  };
}

/** Replace every agent record matching this context with the freshly
 *  imported set. Dedupe is keyed on TWO signals:
 *    (1) any prior record whose `context_name` already equals ctxName,
 *    (2) any prior record whose (machine_host, id) matches one of the
 *        newly-imported agents.
 *  (1) cleans up agents that vanished from the remote. (2) cleans up
 *  stale rows that were imported earlier under a different
 *  `context_name` value (e.g. when remote camc reports a name like
 *  "ssh-test" that has since been renamed locally to "hren") — those
 *  rows would otherwise survive filter (1) and append duplicates.
 *  Agents in other contexts on other machines are untouched. */
function _upsertAgentsForContext(ctxName, newAgents) {
  if (!state.store) state.store = _emptyStore();
  if (!Array.isArray(state.store.agents)) state.store.agents = [];
  const newKeys = new Set(newAgents.map(a => _agentDedupeKey(a)));
  const keep = state.store.agents.filter(a => {
    if ((a.context_name || '') === ctxName) return false;
    const k = _agentDedupeKey(a);
    if (k && newKeys.has(k)) return false;
    return true;
  });
  state.store.agents = keep.concat(newAgents);
  saveStore();
}

/** Run remote `camc --json list` (or fallback) over the injected
 *  ssh-transport and import any active agents into state.store.
 *
 *  `overrides` may carry `{password, passphrase}` for a one-shot
 *  sync that bypasses the credential store entirely. Used by the
 *  source `camui` CLI for debugging password-auth nodes without
 *  Electron `safeStorage`. The overrides are passed straight to
 *  the SSH transport (briefly in memory) and never persisted, never
 *  echoed in the response body, never written to the log buffer.
 *
 *  Returns one of:
 *    { ok: true,  imported, total, results: { camc: 'updated'|'unchanged' } }
 *    { ok: false, error, detail, results: { camc: 'failed' } }
 */
async function _syncContextAgents(ctx, overrides = {}) {
  if (!ctx || !ctx.machine || ctx.machine.type !== 'ssh') {
    return {
      ok:      false,
      error:   'not_ssh',
      detail:  `context "${ctx && ctx.name || '?'}" is not an SSH context`,
      results: { camc: 'failed' },
    };
  }
  if (!_sshTransport || typeof _sshTransport.execRemote !== 'function') {
    return {
      ok:      false,
      error:   'ssh_transport_unavailable',
      detail:  'embedded Hub has no SSH transport configured',
      results: { camc: 'failed' },
    };
  }
  const m = ctx.machine;
  const baseOpts = {
    host:        m.host,
    user:        m.user,
    port:        m.port || 22,
    auth_method: m.auth_method || (m.key_file ? 'key' : 'agent'),
    key_file:    m.key_file || '',
    timeout_ms:  SYNC_DEFAULT_TIMEOUT_MS,
  };
  // Decrypt the stored credential just before handing it to the
  // transport. Stays main-process-only. One-shot overrides (CLI
  // debug path) take precedence over the persisted credential and
  // are never written to disk.
  if (baseOpts.auth_method === 'password') {
    const pw = (typeof overrides.password === 'string' && overrides.password)
      ? overrides.password
      : _credentialFor(ctx);
    if (pw == null || pw === '') {
      return {
        ok:      false,
        error:   'credential_missing',
        detail:  'password auth is configured but no remembered or one-shot password is available',
        results: { camc: 'failed' },
      };
    }
    baseOpts.password = pw;
  } else if (baseOpts.auth_method === 'key') {
    const pp = (typeof overrides.passphrase === 'string' && overrides.passphrase)
      ? overrides.passphrase
      : _credentialFor(ctx);
    if (pp != null) baseOpts.passphrase = pp;
  }

  const ready = await _ensureRemoteCamc(baseOpts);
  if (!ready.ok) {
    pushLog('warn', `sync ${ctx.name} failed: ${ready.error}`);
    return {
      ok:      false,
      error:   ready.error || 'remote_camc_unavailable',
      detail:  ready.detail || 'failed to prepare ~/.cam/camc on remote host',
      results: { camc: 'failed' },
    };
  }

  const res = await _sshTransport.execRemote({ ...baseOpts, command: `${REMOTE_CAMC} --json list` });
  if (!res || !res.ok) {
    const err = (res || {});
    let code = err.error || 'exec_failed';
    if (code === 'remote_nonzero' && /not found|No such file/i.test(err.detail || err.stderr || '')) {
      code = 'camc_missing';
    }
    pushLog('warn', `sync ${ctx.name} failed: ${code}`);
    return {
      ok:      false,
      error:   code,
      detail:  err.detail || err.stderr || 'unknown sync failure',
      results: { camc: 'failed' },
    };
  }

  let parsed;
  try { parsed = JSON.parse(res.stdout || '[]'); }
  catch (e) {
    pushLog('warn', `sync ${ctx.name}: invalid JSON from remote camc`);
    return {
      ok:      false,
      error:   'invalid_json',
      detail:  `remote camc did not return JSON: ${e && e.message}`,
      results: { camc: 'failed' },
    };
  }
  if (!Array.isArray(parsed)) {
    return {
      ok:      false,
      error:   'invalid_json',
      detail:  'remote camc returned a non-array JSON body',
      results: { camc: 'failed' },
    };
  }

  // Filter out clearly-broken records (no id) but otherwise import as-is.
  const normalized = parsed
    .map(r => _normalizeAgent(r, ctx))
    .filter(r => r && r.id);

  // Remember the previous count so we can report updated/unchanged.
  const prev = (state.store && state.store.agents)
    ? state.store.agents.filter(a => (a.context_name || '') === ctx.name)
    : [];
  _upsertAgentsForContext(ctx.name, normalized);

  // Mark context last_used_at so future sync deltas have a timestamp.
  if (state.store) {
    const idx = state.store.contexts.findIndex(c => c.name === ctx.name);
    if (idx >= 0) {
      state.store.contexts[idx].last_used_at = nowIso();
      saveStore();
    }
  }

  // results: 'updated' when the imported set differs in any way from
  // the previous snapshot, 'unchanged' otherwise. Order-independent
  // shallow comparison keyed on id+status+state.
  function fp(a) { return `${a.id}|${a.status}|${a.state}|${a.task_name}|${a.updated_at || ''}`; }
  const prevSig = new Set(prev.map(fp));
  const newSig  = new Set(normalized.map(fp));
  const same = (prevSig.size === newSig.size)
    && [...prevSig].every(k => newSig.has(k));
  const status = same ? 'unchanged' : 'updated';

  pushLog('info', `sync ${ctx.name}: ${status} (${normalized.length} agent(s))`);
  return {
    ok:       true,
    imported: normalized.length,
    total:    parsed.length,
    results:  { camc: status },
  };
}

/** Look up an agent and its owning context from the local store.
 *  Returns `{ agent, ctx }` or `{ error }` shape so callers can map
 *  the failure to a useful UI message instead of an empty body. */
function _contextForAgent(agentId) {
  if (!state.store) return { error: 'store_unavailable' };
  const id = decodeURIComponent(String(agentId || ''));
  const agents = Array.isArray(state.store.agents) ? state.store.agents : [];
  const candidates = agents.filter(a => a && (String(a.id || '') === id || String(a.id || '').startsWith(id)));
  if (!candidates.length) return { error: 'agent_not_found' };
  const ctxs = Array.isArray(state.store.contexts) ? state.store.contexts : [];
  for (const agent of candidates) {
    const byName = ctxs.find(c => c && c.name === agent.context_name);
    if (byName) return { agent, ctx: byName };
  }
  for (const agent of candidates) {
    const byMachine = ctxs.find((ctx) => {
      const m = (ctx && ctx.machine) || {};
      return (m.type || 'local') === (agent.machine_type || agent.transport_type || 'local')
        && (m.host || '') === (agent.machine_host || '')
        && (m.user || '') === (agent.machine_user || '')
        && String(m.port == null ? '' : m.port) === String(agent.machine_port == null ? '' : agent.machine_port);
    });
    if (byMachine) return { agent, ctx: byMachine };
  }
  return { error: 'context_not_found', agent: candidates[0] };
}

/** Run `~/.cam/camc <args>` on a remote context via the injected SSH
 *  transport. Bootstraps the bundled camc to that exact path first
 *  when the remote file is missing, not executable, or hash-different
 *  from the bundled copy.
 *  Returns `{ ok: true, stdout, stderr }` or `{ ok: false, error,
 *  detail }`. Pure execution helper — does not mutate the store. */
function _bundledCamcPath() {
  const candidates = [];
  if (process.resourcesPath) {
    candidates.push(path.join(process.resourcesPath, 'camc', 'camc'));
  }
  candidates.push(path.resolve(__dirname, '..', '..', '..', 'src', 'camc'));
  candidates.push(path.resolve(__dirname, '..', '..', '..', 'dist', 'camc'));
  for (const c of candidates) {
    try { if (fs.statSync(c).isFile()) return c; } catch (_) {}
  }
  return null;
}

function _readBundledCamc() {
  const p = _bundledCamcPath();
  if (!p) return { error: 'bundled_camc_missing', detail: 'bundled camc was not found in resources/camc/camc, src/camc, or dist/camc' };
  try {
    const content = fs.readFileSync(p);
    return {
      content,
      path: p,
      hash: crypto.createHash('md5').update(content).digest('hex').slice(0, 12),
    };
  }
  catch (e) { return { error: 'bundled_camc_read_failed', detail: e && e.message }; }
}

async function _ensureRemoteCamc(baseOpts) {
  // Test stubs used by source smokes may not implement uploads. In
  // that case, assume the stub has made camc available and keep the
  // older tests focused on list/capture behavior.
  if (!_sshTransport || typeof _sshTransport.writeRemoteFile !== 'function') {
    return { ok: true, skipped: 'writeRemoteFile_unavailable' };
  }

  const local = _readBundledCamc();
  if (local.error) return { ok: false, error: local.error, detail: local.detail };

  const remoteHash = await _sshTransport.execRemote({
    ...baseOpts,
    command: `bash -c 'test -x ${REMOTE_CAMC} && md5sum ${REMOTE_CAMC} 2>/dev/null | cut -c1-12'`,
  });
  const remote = remoteHash && remoteHash.ok ? String(remoteHash.stdout || '').trim() : '';
  if (remote && remote === local.hash) {
    return { ok: true, present: true, hash: remote };
  }

  const mkdir = await _sshTransport.execRemote({ ...baseOpts, command: 'mkdir -p ~/.cam' });
  if (!mkdir || !mkdir.ok) {
    return { ok: false, error: mkdir && mkdir.error || 'remote_mkdir_failed', detail: mkdir && (mkdir.detail || mkdir.stderr) || 'mkdir -p ~/.cam failed' };
  }

  const uploaded = await _sshTransport.writeRemoteFile({
    ...baseOpts,
    remotePath: REMOTE_CAMC_UPLOAD_PATH,
    content: local.content,
  });
  if (!uploaded || !uploaded.ok) {
    return { ok: false, error: uploaded && uploaded.error || 'remote_camc_upload_failed', detail: uploaded && uploaded.detail || 'failed to upload bundled camc' };
  }

  const install = await _sshTransport.execRemote({ ...baseOpts, command: `chmod 700 ${REMOTE_CAMC_UPLOAD_PATH} && mv ${REMOTE_CAMC_UPLOAD_PATH} ${REMOTE_CAMC}` });
  if (!install || !install.ok) {
    return { ok: false, error: install && install.error || 'remote_camc_install_failed', detail: install && (install.detail || install.stderr) || 'failed to install ~/.cam/camc' };
  }

  const verify = await _sshTransport.execRemote({ ...baseOpts, command: `test -x ${REMOTE_CAMC}` });
  if (!verify || !verify.ok) {
    return { ok: false, error: verify && verify.error || 'remote_camc_verify_failed', detail: verify && (verify.detail || verify.stderr) || '~/.cam/camc is not executable after upload' };
  }
  const action = remote ? 'updated' : 'installed';
  pushLog('info', `${action} bundled camc on ${baseOpts.user}@${baseOpts.host}:${baseOpts.port || 22}`);
  return { ok: true, installed: !remote, updated: !!remote, hash: local.hash };
}

function _shellQuote(s) {
  return `'${String(s == null ? '' : s).replace(/'/g, `'\\''`)}'`;
}


function _timestampCompact() {
  const d = new Date();
  const pad = (n) => String(n).padStart(2, '0');
  return `${d.getFullYear()}${pad(d.getMonth() + 1)}${pad(d.getDate())}-${pad(d.getHours())}${pad(d.getMinutes())}${pad(d.getSeconds())}`;
}

function _safeUploadFilename(name) {
  let safe = String(name || '').replace(/[^A-Za-z0-9_.-]/g, '_');
  safe = safe.replace(/^\.+/, '').slice(0, 160);
  return safe || 'image.png';
}

function _decodeUploadData(data) {
  const raw = String(data || '').replace(/\s+/g, '');
  if (!raw) return { error: 'missing_data', detail: 'data is required' };
  if (!/^[A-Za-z0-9+/]*={0,2}$/.test(raw) || raw.length % 4 === 1) {
    return { error: 'invalid_base64', detail: 'Invalid base64 data' };
  }
  try {
    const buf = Buffer.from(raw, 'base64');
    if (!buf.length) return { error: 'invalid_base64', detail: 'Invalid base64 data' };
    return { content: buf };
  } catch (e) {
    return { error: 'invalid_base64', detail: e && e.message || 'Invalid base64 data' };
  }
}

/* ─────────────── Workspace Browser (CAM-DESK-FILE-010..017) ───────────────
 *
 * Read-only directory listing + file read for the agent's working
 * directory. The frontend's new Browse output mode hits this via
 * agent-scoped endpoints; the same helpers also back the
 * compatibility context-scoped endpoints below so mobile/Relay
 * callers can drop in without remembering to switch routes.
 *
 * Path safety:
 *   - The root is whatever `agent.context_path || agent.path ||
 *     ctx.path` resolves to. We treat it as an opaque string from
 *     the agent record; we never let the renderer pass a root.
 *   - Subpaths are normalized with `posix.normalize` after stripping
 *     leading `/`. We reject any subpath that starts with `..`,
 *     contains `..` after normalize, or contains a `\0` byte. The
 *     final joined path is reconstructed from the root + cleaned
 *     subpath; we do NOT call `path.resolve` against the local
 *     process — the root is a REMOTE path.
 *   - For local-type contexts, we additionally verify the joined
 *     real path stays under the realpath'd root using
 *     `fs.realpathSync.native`. SFTP paths cannot be realpath'd
 *     locally so we trust the normalized join + reject literal `..`
 *     for the remote case.
 *
 * Response shapes (mirror docs):
 *   list: { scope, agent_id?, context_name?, root, path, parent,
 *           entries: [{name,type,size,mtime?}] }
 *   read: { scope, agent_id?, context_name?, root, path, binary,
 *           size, content }   // content = utf-8 text or base64 when binary
 */
const WORKSPACE_FILE_MAX_BYTES = 5 * 1024 * 1024;

function _resolveBrowseRoot(agent, ctx) {
  if (agent && typeof agent.context_path === 'string' && agent.context_path) return agent.context_path;
  if (agent && typeof agent.path === 'string' && agent.path) return agent.path;
  if (ctx && typeof ctx.path === 'string' && ctx.path) return ctx.path;
  return '';
}

function _cleanBrowseSubpath(raw) {
  let s = String(raw == null ? '' : raw);
  if (s.includes('\0')) return { error: 'invalid_path', detail: 'NUL byte in path' };
  // Normalize separators to forward slashes; SFTP/POSIX paths are
  // forward-slash even when the renderer runs on Windows.
  s = s.replace(/\\/g, '/');
  // Strip leading slashes — sub is always relative to root.
  while (s.startsWith('/')) s = s.slice(1);
  if (!s || s === '.' || s === './') return { sub: '' };
  // Refuse any segment of `..` or a literal `..` anywhere.
  const segs = s.split('/').filter(Boolean);
  for (const seg of segs) {
    if (seg === '..') return { error: 'path_traversal', detail: 'parent traversal not allowed' };
    if (seg === '.')  continue;
  }
  // Drive-letter / UNC absolute escape (defense in depth).
  if (/^[A-Za-z]:[\\/]/.test(s) || s.startsWith('//') || s.startsWith('\\\\')) {
    return { error: 'absolute_path', detail: 'absolute path not allowed' };
  }
  return { sub: segs.filter(p => p !== '.').join('/') };
}

function _joinBrowsePath(root, sub) {
  if (!sub) return root;
  // Use POSIX join — remote roots are POSIX even on Windows-hosted
  // Electron via SFTP. Strip any trailing slash on root for safety.
  const r = root.replace(/[\\/]+$/, '');
  // Replace any host separators with forward slash and trim leading
  // slashes (sub already validated by _cleanBrowseSubpath).
  return r + '/' + sub;
}

function _parentBrowsePath(sub) {
  if (!sub || sub === '') return null;
  const segs = sub.split('/').filter(Boolean);
  if (segs.length <= 1) return '';
  return segs.slice(0, -1).join('/');
}

function _localPath(remotePath) {
  // Convert a POSIX-style "remote" path back to the local OS path
  // for the local-context branch. On Linux this is identity. On
  // Windows the local renderer is rare for Browse v0; we still
  // normalize separators to be safe.
  if (process.platform === 'win32') {
    return remotePath.replace(/\//g, path.sep);
  }
  return remotePath;
}

function _safeLocalPathUnderRoot(rootAbs, full) {
  try {
    const realRoot = fs.realpathSync.native(rootAbs);
    let realFull;
    try { realFull = fs.realpathSync.native(full); }
    catch { realFull = full; }
    if (realFull === realRoot) return true;
    return realFull.startsWith(realRoot + path.sep) || realFull.startsWith(realRoot + '/');
  } catch {
    return false;
  }
}

async function _browseList({ agent, ctx, root, sub }) {
  const isLocal = !ctx || !ctx.machine || ctx.machine.type !== 'ssh';
  const fullRemote = _joinBrowsePath(root, sub);

  if (isLocal) {
    const rootAbs = _localPath(root);
    const fullAbs = _localPath(fullRemote);
    if (!_safeLocalPathUnderRoot(rootAbs, fullAbs)) {
      return { error: 'path_traversal', detail: 'resolved path is outside the workspace root' };
    }
    let dirents;
    try {
      dirents = fs.readdirSync(fullAbs, { withFileTypes: true });
    } catch (e) {
      const code = e && e.code;
      return {
        error:  code === 'ENOENT' ? 'not_found' : (code === 'EACCES' ? 'permission_denied' : 'list_failed'),
        detail: e && e.message,
      };
    }
    const entries = [];
    for (const d of dirents) {
      const name = d.name;
      if (!name || name === '.' || name === '..') continue;
      let size = 0;
      let mtime = null;
      try {
        const st = fs.statSync(path.join(fullAbs, name));
        if (st && st.size != null) size = st.size;
        if (st && st.mtime) mtime = Math.floor(st.mtime.getTime() / 1000);
      } catch { /* ignore per-entry errors */ }
      entries.push({
        name,
        type: d.isDirectory() ? 'dir' : 'file',
        size: d.isDirectory() ? 0 : size,
        mtime,
      });
    }
    entries.sort((a, b) => {
      if (a.type !== b.type) return a.type === 'dir' ? -1 : 1;
      return a.name.localeCompare(b.name);
    });
    return { entries };
  }

  // SSH branch via SFTP — uses the existing pooled connection.
  if (!_sshTransport || typeof _sshTransport.listRemoteFiles !== 'function') {
    return { error: 'ssh_transport_unavailable', detail: 'embedded Hub has no SSH transport configured' };
  }
  const baseBuilt = _sshBaseOptsForContext(ctx);
  if (baseBuilt.error) return { error: baseBuilt.error, detail: baseBuilt.detail };
  const res = await _sshTransport.listRemoteFiles({
    ...baseBuilt.opts,
    remotePath: fullRemote,
  });
  if (!res || !res.ok) {
    return { error: (res && res.error) || 'sftp_readdir_failed', detail: (res && res.detail) || 'list failed' };
  }
  return { entries: res.entries || [] };
}

async function _browseRead({ agent, ctx, root, sub }) {
  if (!sub) return { error: 'missing_path', detail: 'path is required' };
  const isLocal = !ctx || !ctx.machine || ctx.machine.type !== 'ssh';
  const fullRemote = _joinBrowsePath(root, sub);

  if (isLocal) {
    const rootAbs = _localPath(root);
    const fullAbs = _localPath(fullRemote);
    if (!_safeLocalPathUnderRoot(rootAbs, fullAbs)) {
      return { error: 'path_traversal', detail: 'resolved path is outside the workspace root' };
    }
    let st;
    try { st = fs.statSync(fullAbs); }
    catch (e) {
      const code = e && e.code;
      return {
        error:  code === 'ENOENT' ? 'not_found' : (code === 'EACCES' ? 'permission_denied' : 'stat_failed'),
        detail: e && e.message,
      };
    }
    if (st.isDirectory()) return { error: 'is_directory', detail: 'path is a directory' };
    if (st.size > WORKSPACE_FILE_MAX_BYTES) {
      return { error: 'too_large', detail: `file is ${st.size} bytes (max ${WORKSPACE_FILE_MAX_BYTES})`, size: st.size };
    }
    let data;
    try { data = fs.readFileSync(fullAbs); }
    catch (e) {
      return { error: 'read_failed', detail: e && e.message };
    }
    return _packBrowseRead(data, st.size);
  }

  if (!_sshTransport || typeof _sshTransport.readRemoteFile !== 'function') {
    return { error: 'ssh_transport_unavailable', detail: 'embedded Hub has no SSH transport configured' };
  }
  const baseBuilt = _sshBaseOptsForContext(ctx);
  if (baseBuilt.error) return { error: baseBuilt.error, detail: baseBuilt.detail };
  const res = await _sshTransport.readRemoteFile({
    ...baseBuilt.opts,
    remotePath: fullRemote,
    maxBytes:   WORKSPACE_FILE_MAX_BYTES,
  });
  if (!res || !res.ok) {
    return {
      error:  (res && res.error)  || 'sftp_read_failed',
      detail: (res && res.detail) || 'read failed',
      size:   (res && res.size)   != null ? res.size : undefined,
    };
  }
  return _packBrowseRead(res.content, res.size);
}

function _packBrowseRead(buf, sizeFromStat) {
  const data = Buffer.isBuffer(buf) ? buf : Buffer.from(buf || '');
  const size = Number.isFinite(sizeFromStat) ? sizeFromStat : data.length;
  if (data.length === 0) return { binary: false, size: 0, content: '' };
  // Binary heuristic: NUL byte in first 8 KiB → binary. Matches the
  // Python files.py route so mobile + desktop stay consistent.
  const head = data.slice(0, Math.min(data.length, 8192));
  let isBinary = false;
  for (let i = 0; i < head.length; i++) {
    if (head[i] === 0) { isBinary = true; break; }
  }
  if (isBinary) {
    return { binary: true, size, content: data.toString('base64') };
  }
  let text;
  try { text = data.toString('utf8'); }
  catch { text = data.toString('latin1'); }
  return { binary: false, size, content: text };
}

async function _browseAgentList(agentId, rawPath) {
  const resolved = _contextForAgent(agentId);
  if (resolved.error && resolved.error !== 'context_not_found') {
    return { httpStatus: resolved.error === 'agent_not_found' ? 404 : 502, body: { error: resolved.error, detail: `Browse unavailable: ${resolved.error}` } };
  }
  const agent = resolved.agent || {};
  const ctx   = resolved.ctx  || null;
  const root  = _resolveBrowseRoot(agent, ctx);
  if (!root) {
    return { httpStatus: 502, body: { error: 'workspace_missing', detail: 'Agent has no working directory recorded' } };
  }
  const cleaned = _cleanBrowseSubpath(rawPath);
  if (cleaned.error) return { httpStatus: 400, body: { error: cleaned.error, detail: cleaned.detail } };
  const sub = cleaned.sub || '';

  const res = await _browseList({ agent, ctx, root, sub });
  if (res.error) {
    const badArgs = new Set(['invalid_path', 'path_traversal', 'absolute_path', 'is_directory']);
    const status = res.error === 'not_found'
      ? 404
      : (badArgs.has(res.error) ? 400 : (res.error === 'permission_denied' ? 403 : 502));
    return { httpStatus: status, body: { error: res.error, detail: res.detail } };
  }
  return {
    httpStatus: 200,
    body: {
      scope:        'agent',
      agent_id:     agent.id || String(agentId),
      context_name: agent.context_name || (ctx && ctx.name) || null,
      root,
      path:         sub,
      parent:       _parentBrowsePath(sub),
      entries:      res.entries,
    },
  };
}

async function _browseAgentRead(agentId, rawPath) {
  const resolved = _contextForAgent(agentId);
  if (resolved.error && resolved.error !== 'context_not_found') {
    return { httpStatus: resolved.error === 'agent_not_found' ? 404 : 502, body: { error: resolved.error, detail: `Browse unavailable: ${resolved.error}` } };
  }
  const agent = resolved.agent || {};
  const ctx   = resolved.ctx  || null;
  const root  = _resolveBrowseRoot(agent, ctx);
  if (!root) {
    return { httpStatus: 502, body: { error: 'workspace_missing', detail: 'Agent has no working directory recorded' } };
  }
  const cleaned = _cleanBrowseSubpath(rawPath);
  if (cleaned.error) return { httpStatus: 400, body: { error: cleaned.error, detail: cleaned.detail } };
  const sub = cleaned.sub || '';

  const res = await _browseRead({ agent, ctx, root, sub });
  if (res.error) {
    const badArgs = new Set(['missing_path', 'invalid_path', 'path_traversal', 'absolute_path', 'is_directory', 'too_large']);
    const status = res.error === 'not_found'
      ? 404
      : (badArgs.has(res.error) ? 400 : (res.error === 'permission_denied' ? 403 : 502));
    return {
      httpStatus: status,
      body: { error: res.error, detail: res.detail, size: res.size },
    };
  }
  return {
    httpStatus: 200,
    body: {
      scope:        'agent',
      agent_id:     agent.id || String(agentId),
      context_name: agent.context_name || (ctx && ctx.name) || null,
      root,
      path:         sub,
      binary:       res.binary,
      size:         res.size,
      content:      res.content,
    },
  };
}

async function _browseContextList(ctxNameOrId, rawPath) {
  const ctx = findContextByName(String(ctxNameOrId || '')) || (state.store && Array.isArray(state.store.contexts) ? state.store.contexts.find(c => String(c.id || '') === String(ctxNameOrId)) : null);
  if (!ctx) return { httpStatus: 404, body: { error: 'context_not_found', detail: `Context not found: ${ctxNameOrId}` } };
  const root = ctx.path || '';
  if (!root) return { httpStatus: 502, body: { error: 'workspace_missing', detail: 'Context has no working directory' } };
  const cleaned = _cleanBrowseSubpath(rawPath);
  if (cleaned.error) return { httpStatus: 400, body: { error: cleaned.error, detail: cleaned.detail } };
  const sub = cleaned.sub || '';

  const res = await _browseList({ ctx, root, sub });
  if (res.error) {
    const badArgs = new Set(['invalid_path', 'path_traversal', 'absolute_path', 'is_directory']);
    const status = res.error === 'not_found'
      ? 404
      : (badArgs.has(res.error) ? 400 : (res.error === 'permission_denied' ? 403 : 502));
    return { httpStatus: status, body: { error: res.error, detail: res.detail } };
  }
  return {
    httpStatus: 200,
    body: {
      scope:        'context',
      context_id:   String(ctx.id || ''),
      context_name: ctx.name,
      root,
      path:         sub,
      parent:       _parentBrowsePath(sub),
      entries:      res.entries,
    },
  };
}

async function _browseContextRead(ctxNameOrId, rawPath) {
  const ctx = findContextByName(String(ctxNameOrId || '')) || (state.store && Array.isArray(state.store.contexts) ? state.store.contexts.find(c => String(c.id || '') === String(ctxNameOrId)) : null);
  if (!ctx) return { httpStatus: 404, body: { error: 'context_not_found', detail: `Context not found: ${ctxNameOrId}` } };
  const root = ctx.path || '';
  if (!root) return { httpStatus: 502, body: { error: 'workspace_missing', detail: 'Context has no working directory' } };
  const cleaned = _cleanBrowseSubpath(rawPath);
  if (cleaned.error) return { httpStatus: 400, body: { error: cleaned.error, detail: cleaned.detail } };
  const sub = cleaned.sub || '';

  const res = await _browseRead({ ctx, root, sub });
  if (res.error) {
    const badArgs = new Set(['missing_path', 'invalid_path', 'path_traversal', 'absolute_path', 'is_directory', 'too_large']);
    const status = res.error === 'not_found'
      ? 404
      : (badArgs.has(res.error) ? 400 : (res.error === 'permission_denied' ? 403 : 502));
    return {
      httpStatus: status,
      body: { error: res.error, detail: res.detail, size: res.size },
    };
  }
  return {
    httpStatus: 200,
    body: {
      scope:        'context',
      context_id:   String(ctx.id || ''),
      context_name: ctx.name,
      root,
      path:         sub,
      binary:       res.binary,
      size:         res.size,
      content:      res.content,
    },
  };
}

function _sshBaseOptsForContext(ctx, timeoutMs = SYNC_DEFAULT_TIMEOUT_MS) {
  if (!ctx || !ctx.machine || ctx.machine.type !== 'ssh') {
    return { error: 'not_ssh', detail: `context "${(ctx && ctx.name) || '?'}" is not an SSH context` };
  }
  if (!_sshTransport || typeof _sshTransport.execRemote !== 'function') {
    return { error: 'ssh_transport_unavailable', detail: 'embedded Hub has no SSH transport configured' };
  }
  const m = ctx.machine;
  const opts = {
    host:        m.host,
    user:        m.user,
    port:        m.port || 22,
    auth_method: m.auth_method || (m.key_file ? 'key' : 'agent'),
    key_file:    m.key_file || '',
    timeout_ms:  timeoutMs,
  };
  if (opts.auth_method === 'password') {
    const pw = _credentialFor(ctx);
    if (pw == null || pw === '') {
      return { error: 'credential_missing', detail: 'password auth is configured but no remembered password is available' };
    }
    opts.password = pw;
  } else if (opts.auth_method === 'key') {
    const pp = _credentialFor(ctx);
    if (pp != null) opts.passphrase = pp;
  }
  return { opts };
}


function _validTmuxKey(key) {
  return /^[A-Za-z0-9_-]{1,32}$/.test(String(key || ''));
}

async function _sendAgentKey(agentId, key) {
  const k = String(key || '').trim();
  if (!k) return { ok: false, error: 'missing_key', detail: 'key is required' };
  if (!_validTmuxKey(k)) return { ok: false, error: 'invalid_key', detail: `invalid key: ${k}` };
  const resolved = _contextForAgent(agentId);
  if (resolved.error) return { ok: false, error: resolved.error, detail: `Key unavailable: ${resolved.error}` };
  const agent = resolved.agent || {};
  const terminal = ['completed', 'failed', 'timeout', 'killed'].includes(String(agent.status || '').toLowerCase());
  if (terminal) return { ok: false, error: 'agent_not_running', detail: 'Agent is not running' };
  const exec = await _execCamcOnContext(resolved.ctx, ['key', agentId, '--key', k], { timeoutMs: Math.max(SYNC_DEFAULT_TIMEOUT_MS, 30000) });
  if (!exec.ok) return { ok: false, error: exec.error || 'send_key_failed', detail: exec.detail || exec.stderr || 'failed to send key' };
  return { ok: true, stdout: exec.stdout || '', stderr: exec.stderr || '' };
}

async function _uploadAgentFile(agentId, body) {
  const resolved = _contextForAgent(agentId);
  if (resolved.error) return { ok: false, error: resolved.error, detail: `Upload unavailable: ${resolved.error}` };
  const agent = resolved.agent || {};
  const ctx = resolved.ctx;
  const terminal = ['completed', 'failed', 'timeout', 'killed'].includes(String(agent.status || '').toLowerCase());
  if (terminal) return { ok: false, error: 'agent_not_running', detail: 'Agent is not running' };
  if (!_sshTransport || typeof _sshTransport.writeRemoteFile !== 'function') {
    return { ok: false, error: 'ssh_upload_unavailable', detail: 'embedded Hub SSH transport cannot upload files' };
  }

  const filename = body && body.filename != null ? String(body.filename) : '';
  if (!filename.trim()) return { ok: false, error: 'missing_filename', detail: 'filename is required' };
  const decoded = _decodeUploadData(body && body.data);
  if (decoded.error) return { ok: false, error: decoded.error, detail: decoded.detail };

  const contextPath = String(agent.context_path || agent.path || (ctx && ctx.path) || '').replace(/\/+$/, '');
  if (!contextPath) return { ok: false, error: 'working_dir_missing', detail: 'Agent has no working directory' };

  const baseBuilt = _sshBaseOptsForContext(ctx, Math.max(SYNC_DEFAULT_TIMEOUT_MS, 60000));
  if (baseBuilt.error) return { ok: false, error: baseBuilt.error, detail: baseBuilt.detail };
  const baseOpts = baseBuilt.opts;
  const dir = `${contextPath}/.cam-images`;
  const destPath = `${dir}/${_timestampCompact()}-${_safeUploadFilename(filename)}`;

  const mkdir = await _sshTransport.execRemote({ ...baseOpts, command: `mkdir -p ${_shellQuote(dir)}` });
  if (!mkdir || !mkdir.ok) {
    return { ok: false, error: mkdir && mkdir.error || 'remote_mkdir_failed', detail: mkdir && (mkdir.detail || mkdir.stderr) || 'failed to create remote upload directory' };
  }
  const wrote = await _sshTransport.writeRemoteFile({
    ...baseOpts,
    remotePath: destPath,
    content:    decoded.content,
  });
  if (!wrote || !wrote.ok) {
    return { ok: false, error: wrote && wrote.error || 'remote_upload_failed', detail: wrote && wrote.detail || 'failed to write remote file' };
  }
  pushLog('info', `upload ${agentId}: ${destPath} (${decoded.content.length} bytes)`);
  return { ok: true, path: destPath, size: decoded.content.length };
}

function _captureArgs(id, lines, format, withFormat = true) {
  const args = ['capture', id, '--lines', String(lines)];
  // Older deployed camc builds do not accept `--format plain`; plain
  // is the default, so omit the flag for maximum compatibility. Only
  // request ANSI when the UI explicitly asks for it.
  if (withFormat && format === 'ansi') args.push('--format', 'ansi');
  return args;
}

function _isUnsupportedCaptureFormat(exec) {
  const detail = `${exec && exec.detail || ''}
${exec && exec.stderr || ''}`;
  return /unrecognized arguments:\s*--format/i.test(detail);
}

async function _sendAgentInput(agentId, text, sendEnter = true) {
  const resolved = _contextForAgent(agentId);
  if (resolved.error) return { ok: false, error: resolved.error, detail: `Input unavailable: ${resolved.error}` };
  const ctx = resolved.ctx;
  if (!ctx || !ctx.machine || ctx.machine.type !== 'ssh') {
    return { ok: false, error: 'not_ssh', detail: `context "${(ctx && ctx.name) || '?'}" is not an SSH context` };
  }
  if (!_sshTransport || typeof _sshTransport.execRemote !== 'function') {
    return { ok: false, error: 'ssh_transport_unavailable', detail: 'embedded Hub has no SSH transport configured' };
  }
  if (typeof _sshTransport.writeRemoteFile !== 'function') {
    return { ok: false, error: 'ssh_upload_unavailable', detail: 'embedded Hub SSH transport cannot upload long input payloads' };
  }

  const m = ctx.machine;
  const baseOpts = {
    host:        m.host,
    user:        m.user,
    port:        m.port || 22,
    auth_method: m.auth_method || (m.key_file ? 'key' : 'agent'),
    key_file:    m.key_file || '',
    timeout_ms:  SYNC_DEFAULT_TIMEOUT_MS,
  };
  if (baseOpts.auth_method === 'password') {
    const pw = _credentialFor(ctx);
    if (pw == null || pw === '') {
      return { ok: false, error: 'credential_missing', detail: 'password auth is configured but no remembered password is available' };
    }
    baseOpts.password = pw;
  } else if (baseOpts.auth_method === 'key') {
    const pp = _credentialFor(ctx);
    if (pp != null) baseOpts.passphrase = pp;
  }

  const ready = await _ensureRemoteCamc(baseOpts);
  if (!ready.ok) {
    return { ok: false, error: ready.error || 'remote_camc_unavailable', detail: ready.detail || 'failed to prepare ~/.cam/camc on remote host' };
  }

  const nonce = crypto.randomUUID();
  const remotePath = `.cam/camui-input-${nonce}.txt`;
  const remoteScript = `.cam/camui-send-${nonce}.py`;
  const uploaded = await _sshTransport.writeRemoteFile({
    ...baseOpts,
    remotePath,
    content: Buffer.from(String(text || ''), 'utf8'),
  });
  if (!uploaded || !uploaded.ok) {
    return { ok: false, error: uploaded && uploaded.error || 'remote_input_upload_failed', detail: uploaded && uploaded.detail || 'failed to upload input payload' };
  }

  const script = `import os, pathlib, subprocess, sys
agent = sys.argv[1]
path = sys.argv[2]
send_enter = sys.argv[3] == "1"
text = pathlib.Path(path).read_text(encoding="utf-8")
cmd = [os.path.expanduser("~/.cam/camc"), "send", agent, "--text", text]
if not send_enter:
    cmd.append("--no-enter")
try:
    rc = subprocess.call(cmd)
finally:
    for p in (path, __file__):
        try:
            os.remove(p)
        except OSError:
            pass
raise SystemExit(rc)
`;
  const scriptUploaded = await _sshTransport.writeRemoteFile({
    ...baseOpts,
    remotePath: remoteScript,
    content: Buffer.from(script, 'utf8'),
  });
  if (!scriptUploaded || !scriptUploaded.ok) {
    return { ok: false, error: scriptUploaded && scriptUploaded.error || 'remote_script_upload_failed', detail: scriptUploaded && scriptUploaded.detail || 'failed to upload input helper script' };
  }

  const cmd = `python3 ${remoteScript} ${agentId} ${remotePath} ${sendEnter ? '1' : '0'}`;
  const res = await _sshTransport.execRemote({ ...baseOpts, command: cmd, timeout_ms: Math.max(SYNC_DEFAULT_TIMEOUT_MS, 30000) });
  if (!res || !res.ok) {
    return { ok: false, error: res && res.error || 'send_failed', detail: res && (res.detail || res.stderr) || 'remote send failed' };
  }
  return { ok: true, stdout: res.stdout || '', stderr: res.stderr || '' };
}

async function _execCamcOnContext(ctx, camcArgs, { overrides = {}, timeoutMs = SYNC_DEFAULT_TIMEOUT_MS } = {}) {
  if (!ctx || !ctx.machine || ctx.machine.type !== 'ssh') {
    return { ok: false, error: 'not_ssh', detail: `context "${(ctx && ctx.name) || '?'}" is not an SSH context` };
  }
  if (!_sshTransport || typeof _sshTransport.execRemote !== 'function') {
    return { ok: false, error: 'ssh_transport_unavailable', detail: 'embedded Hub has no SSH transport configured' };
  }
  const m = ctx.machine;
  const baseOpts = {
    host:        m.host,
    user:        m.user,
    port:        m.port || 22,
    auth_method: m.auth_method || (m.key_file ? 'key' : 'agent'),
    key_file:    m.key_file || '',
    timeout_ms:  timeoutMs,
  };
  if (baseOpts.auth_method === 'password') {
    const pw = (typeof overrides.password === 'string' && overrides.password)
      ? overrides.password
      : _credentialFor(ctx);
    if (pw == null || pw === '') {
      return { ok: false, error: 'credential_missing', detail: 'password auth is configured but no remembered or one-shot password is available' };
    }
    baseOpts.password = pw;
  } else if (baseOpts.auth_method === 'key') {
    const pp = (typeof overrides.passphrase === 'string' && overrides.passphrase)
      ? overrides.passphrase
      : _credentialFor(ctx);
    if (pp != null) baseOpts.passphrase = pp;
  }
  const ready = await _ensureRemoteCamc(baseOpts);
  if (!ready.ok) {
    return { ok: false, error: ready.error || 'remote_camc_unavailable', detail: ready.detail || 'failed to prepare ~/.cam/camc on remote host' };
  }
  const argStr = camcArgs.map(a => String(a)).join(' ');
  const res = await _sshTransport.execRemote({ ...baseOpts, command: `${REMOTE_CAMC} ${argStr}` });
  if (!res || !res.ok) {
    const err = res || {};
    let code = err.error || 'exec_failed';
    if (code === 'remote_nonzero' && /not found|No such file/i.test(err.detail || err.stderr || '')) {
      code = 'camc_missing';
    }
    return { ok: false, error: code, detail: err.detail || err.stderr || 'unknown exec failure', stderr: err.stderr || '', stdout: err.stdout || '' };
  }
  return { ok: true, stdout: String(res.stdout || ''), stderr: String(res.stderr || '') };
}

/* ─────────────── SSH config parser (read-only, no shell) ─────────────── */

function expandHome(p) {
  if (!p) return p;
  if (p === '~' || p.startsWith('~/') || p.startsWith('~\\')) {
    return path.join(os.homedir(), p.slice(1).replace(/^[/\\]/, ''));
  }
  return p;
}

function sshConfigPaths() {
  const out = [];
  const home = os.homedir();
  if (home) out.push(path.join(home, '.ssh', 'config'));
  // Windows ssh-agent / OpenSSH also reads %USERPROFILE%\.ssh\config
  // which is what os.homedir() returns there, so the entry above
  // already covers it. Keeping it as a single path simplifies the
  // policy (one well-known location, no surprises).
  return out;
}

/** Parse a small, conservative subset of OpenSSH client config:
 *  - Host blocks (only entries WITHOUT wildcards `*` or `?`)
 *  - Per-block: HostName, User, Port, IdentityFile, ProxyJump (info only)
 *  - Lines starting with `#` are comments
 *  - `Include` directives are NOT followed in this pass
 *  Returns an array of { alias, hostName, user, port, identityFile }
 *  with identityFile as the raw `IdentityFile` reference (expanded
 *  via ~). Never reads key file contents. */
function parseSshConfig(text) {
  const lines = String(text || '').split(/\r?\n/);
  const blocks = [];
  // OpenSSH applies subsequent options to ALL aliases listed on the
  // current `Host` line (e.g. `Host alpha beta` followed by
  // `HostName h.example` configures BOTH alpha and beta). We track
  // the set of currently-open block objects as `active` and apply
  // each key/value to every one of them.
  let active = [];
  for (const raw of lines) {
    const line = raw.replace(/^\s+|\s+$/g, '');
    if (!line || line.startsWith('#')) continue;
    const m = /^([A-Za-z]+)[\s=]+(.+)$/.exec(line);
    if (!m) continue;
    const key = m[1].toLowerCase();
    const value = m[2].trim();
    if (key === 'host') {
      // Reset the active set to the concrete aliases on this Host
      // line. Wildcards (`*`, `?`) are skipped entirely — they're
      // OpenSSH defaults, not concrete hosts the user can pick.
      active = [];
      for (const alias of value.split(/\s+/)) {
        if (!alias || alias.includes('*') || alias.includes('?')) continue;
        const blk = {
          alias,
          hostName:     null,
          user:         null,
          port:         null,
          identityFile: null,
        };
        blocks.push(blk);
        active.push(blk);
      }
      continue;
    }
    if (active.length === 0) continue;
    let val;
    switch (key) {
      case 'hostname':
        for (const blk of active) blk.hostName = value;
        break;
      case 'user':
        for (const blk of active) blk.user = value;
        break;
      case 'port': {
        const p = Number.parseInt(value, 10);
        if (!Number.isFinite(p) || p < 1 || p > 65535) break;
        for (const blk of active) blk.port = p;
        break;
      }
      case 'identityfile':
        val = expandHome(value);
        for (const blk of active) blk.identityFile = val;
        break;
      default: break;
    }
  }
  return blocks;
}

function sshConfigHosts() {
  const paths = sshConfigPaths();
  const out = {
    source:    null,
    available: false,
    hosts:     [],
    note:      'IdentityFile is returned as a path reference only; key contents are never read by the renderer.',
  };
  for (const p of paths) {
    let text;
    try { text = fs.readFileSync(p, 'utf8'); }
    catch (e) {
      if (e.code !== 'ENOENT') {
        pushLog('warn', `ssh config read failed for ${p}: ${e.message}`);
      }
      continue;
    }
    out.source = p;
    out.available = true;
    const blocks = parseSshConfig(text);
    out.hosts = blocks
      .map((b) => ({
        alias:         b.alias,
        host:          b.hostName || b.alias,
        user:          b.user || '',
        port:          b.port || 22,
        identity_file: b.identityFile || '',
      }))
      .filter((h) => h.host && h.user); // skip entries without enough info
    break; // only the first existing config
  }
  return out;
}

function checkBearer(req) {
  const h = req.headers['authorization'] || req.headers['Authorization'];
  if (!h) return false;
  const m = /^Bearer\s+(\S+)$/i.exec(String(h));
  if (!m) return false;
  return m[1] === state.token;
}

function healthBody() {
  return {
    status:         'ok',
    version:        HUB_PRODUCT_VERSION,
    adapters:       (state.store && state.store.adapters) || DEFAULT_ADAPTERS,
    agents_running: 0,
    agents_total:   (state.store && state.store.agents) ? state.store.agents.length : 0,
    contexts_count: (state.store && state.store.contexts) ? state.store.contexts.length : 0,
  };
}

/* ─────────────── Router ─────────────── */

async function handle(req, res) {
  const { method } = req;
  const url = new URL(req.url, 'http://127.0.0.1');
  const p = url.pathname;

  // Preflight: Chromium emits OPTIONS for any /api/* fetch that
  // includes Authorization or a non-simple method. Answer 204 + CORS
  // headers; bearer auth is enforced on the real request.
  if (method === 'OPTIONS') {
    res.writeHead(204, corsHeaders());
    return res.end();
  }

  // health: no auth (CamApi connect probes /api/contexts with auth, but
  // some operator tools probe /health anonymously).
  if (method === 'GET' && p === '/api/system/health') {
    return sendJson(res, 200, healthBody());
  }

  // Every other /api/* needs bearer auth.
  if (p.startsWith('/api/')) {
    if (!checkBearer(req)) {
      pushLog('warn', `${method} ${p} 401`);
      return sendJson(res, 401, { error: 'unauthorized' });
    }
  } else {
    // No non-/api/* surface in this pass.
    return send404(res);
  }

  // /api/system/config
  if (method === 'GET' && p === '/api/system/config') {
    return sendJson(res, 200, {
      version:  HUB_PRODUCT_VERSION,
      data_dir: state.dataDir || null,
    });
  }

  // /api/system/ssh-config — read-only suggestion list for the Nodes
  // import UI. Returns parsed entries from the user's `~/.ssh/config`
  // (CAM-DESK-DIRECT-017). Never reads private-key contents — key
  // file values are returned as paths only.
  if (method === 'GET' && p === '/api/system/ssh-config') {
    try {
      return sendJson(res, 200, sshConfigHosts());
    } catch (e) {
      pushLog('warn', `ssh-config read failed: ${e.message}`);
      return sendJson(res, 200, { available: false, source: null, hosts: [], note: 'ssh config not readable' });
    }
  }

  // WebSocket request (CamApi attempts /api/ws?token=...). We don't
  // implement WS in this pass; return 426 so the renderer's event
  // stream fallback closes cleanly and polling continues.
  if (p === '/api/ws') {
    res.writeHead(426, {
      'Content-Type': 'application/json; charset=utf-8',
      'Connection':   'close',
    });
    return res.end(JSON.stringify({ error: 'upgrade_required', detail: 'WS deferred in embedded Hub' }));
  }

  // Contexts — CRUD against the embedded store
  // (CAM-DESK-DIRECT-014..016).
  if (p === '/api/contexts') {
    if (method === 'GET') {
      return sendJson(res, 200, { contexts: state.store.contexts });
    }
    if (method === 'POST') {
      let body;
      try { body = await readJsonBody(req); }
      catch (e) { return send400(res, e.message); }
      // Pre-check dup name BEFORE buildContextRecord. buildContextRecord
      // calls _saveRememberedSecret() when remember_password /
      // remember_passphrase is true, which would persist a credential
      // blob whose ref nothing ever references — orphaning it on disk.
      // We still let buildContextRecord report invalid_name for shape
      // problems, but only after we've confirmed the name is free.
      const requestedName = body && body.name != null ? String(body.name).trim() : '';
      if (requestedName && NAME_RE.test(requestedName) && findContextByName(requestedName)) {
        return sendJson(res, 400, { error: 'duplicate_name', detail: `context "${requestedName}" already exists` });
      }
      const built = buildContextRecord(body || {});
      if (built.error) return send400(res, built.detail || built.error, built.error);
      // Re-check the dup case after build in case of a TOCTOU race —
      // single-process server with no async between the pre-check and
      // here, so this is belt-and-suspenders.
      if (findContextByName(built.record.name)) {
        // Roll back any credential blob the build path might have just
        // saved for this rejected record.
        _cascadeDeleteCreds(built.record.id);
        return sendJson(res, 400, { error: 'duplicate_name', detail: `context "${built.record.name}" already exists` });
      }
      state.store.contexts.push(built.record);
      saveStore();
      pushLog('info', `context created: ${built.record.name}`);
      return sendJson(res, 201, built.record);
    }
    return send404(res);
  }
  const ctxMatch = /^\/api\/contexts\/([^/]+)(\/.*)?$/.exec(p);
  if (ctxMatch) {
    const ctxName = decodeURIComponent(ctxMatch[1]);
    const sub = ctxMatch[2] || '';
    const existing = findContextByName(ctxName);

    if (method === 'GET' && !sub) {
      if (!existing) return send404(res);
      return sendJson(res, 200, existing);
    }
    if ((method === 'PUT' || method === 'PATCH') && !sub) {
      if (!existing) return send404(res);
      let body;
      try { body = await readJsonBody(req); }
      catch (e) { return send400(res, e.message); }
      const upd = applyContextUpdate(existing, body || {});
      if (upd.error) return send400(res, upd.detail || upd.error, upd.error);
      const idx = state.store.contexts.findIndex(c => c.name === ctxName);
      state.store.contexts[idx] = upd.record;
      saveStore();
      pushLog('info', `context updated: ${ctxName}`);
      return sendJson(res, 200, upd.record);
    }
    if (method === 'DELETE' && !sub) {
      if (!existing) return send404(res);
      const idx = state.store.contexts.findIndex(c => c.name === ctxName);
      state.store.contexts.splice(idx, 1);
      saveStore();
      // Cascade: drop any remembered password/passphrase tied to
      // this context id so they don't linger as orphans in the
      // credential store (CAM-DESK-DIRECT-018).
      _cascadeDeleteCreds(existing.id);
      pushLog('info', `context deleted: ${ctxName}`);
      return sendJson(res, 200, { ok: true });
    }
    if (method === 'POST' && sub === '/sync') {
      if (!existing) return send404(res);
      // Optional one-shot credential overrides for debugging via the
      // source `camui` CLI (where Electron safeStorage isn't
      // available). Body is optional; renderer never sends one.
      // Overrides are kept in memory only for the duration of the
      // SSH handshake; not persisted, not logged, not echoed.
      let body = {};
      const ctype = (req.headers['content-type'] || '').toLowerCase();
      if (ctype.includes('application/json')) {
        try { body = await readJsonBody(req); }
        catch (e) { return send400(res, e.message); }
      }
      const overrides = {};
      if (typeof body.password   === 'string' && body.password)   overrides.password   = body.password;
      if (typeof body.passphrase === 'string' && body.passphrase) overrides.passphrase = body.passphrase;
      const result = await _syncContextAgents(existing, overrides);
      // Always 200: the renderer's existing per-context tally relies
      // on `results` + an `ok` flag, not on HTTP status. Auth/connect
      // errors become results.camc='failed' + an `error` code the UI
      // can show as a warning toast.
      return sendJson(res, 200, result);
    }
    if (method === 'POST' && sub === '/copy') return send501(res, 'context copy');
    if (method === 'GET'   && sub === '/files') {
      const subpath = url.searchParams.get('path') || '';
      const out = await _browseContextList(existing.name, subpath);
      return sendJson(res, out.httpStatus, out.body);
    }
    if (method === 'GET'   && sub === '/files/read') {
      const subpath = url.searchParams.get('path') || '';
      const out = await _browseContextRead(existing.name, subpath);
      return sendJson(res, out.httpStatus, out.body);
    }
    return send404(res);
  }

  // Agents
  if (p === '/api/agents') {
    if (method === 'GET') {
      _repairStoreAgents();
      return sendJson(res, 200, { agents: state.store.agents });
    }
    if (method === 'POST') return send501(res, 'start agent');
    return send404(res);
  }
  const agentMatch = /^\/api\/agents\/([^/]+)(\/.*)?$/.exec(p);
  if (agentMatch) {
    const sub = agentMatch[2] || '';
    if (method === 'GET' && !sub)                          return send404(res);
    if (method === 'PATCH' && !sub)                        return send501(res, 'edit agent');
    if (method === 'DELETE' && !sub)                       return send501(res, 'stop agent');
    if (method === 'DELETE' && sub === '/history')         return send501(res, 'delete agent history');
    if (method === 'POST'  && sub === '/restart')          return send501(res, 'restart agent');
    if (method === 'POST'  && sub === '/input') {
      let body;
      try { body = await readJsonBody(req); }
      catch (e) { return send400(res, e.message); }
      const text = body && body.text != null ? String(body.text) : '';
      const sendEnter = body && body.send_enter === false ? false : true;
      if (!text) return send400(res, 'text is required', 'missing_text');
      const sent = await _sendAgentInput(agentMatch[1], text, sendEnter);
      if (!sent.ok) {
        pushLog('warn', `input ${agentMatch[1]} failed: ${sent.error}`);
        return sendJson(res, 502, { error: sent.error || 'send_failed', detail: sent.detail || 'send failed' });
      }
      return sendJson(res, 200, { ok: true });
    }
    if (method === 'POST'  && sub === '/key') {
      let body;
      try { body = await readJsonBody(req); }
      catch (e) { return send400(res, e.message); }
      const key = body && body.key != null ? String(body.key) : '';
      const sent = await _sendAgentKey(agentMatch[1], key);
      if (!sent.ok) {
        pushLog('warn', `key ${agentMatch[1]} failed: ${sent.error}`);
        const bad = new Set(['missing_key', 'invalid_key', 'agent_not_running', 'not_ssh', 'credential_missing']);
        const status = sent.error === 'agent_not_found' ? 404 : (bad.has(sent.error) ? 400 : 502);
        return sendJson(res, status, { error: sent.error || 'send_key_failed', detail: sent.detail || 'send key failed' });
      }
      return sendJson(res, 200, { ok: true });
    }
    if (method === 'POST'  && sub === '/upload') {
      let body;
      try { body = await readJsonBody(req); }
      catch (e) { return send400(res, e.message, e.message === 'body_too_large' ? 'body_too_large' : 'bad_request'); }
      const uploaded = await _uploadAgentFile(agentMatch[1], body || {});
      if (!uploaded.ok) {
        pushLog('warn', `upload ${agentMatch[1]} failed: ${uploaded.error}`);
        const bad = new Set(['missing_filename', 'missing_data', 'invalid_base64', 'working_dir_missing', 'agent_not_running', 'not_ssh', 'credential_missing']);
        const status = uploaded.error === 'agent_not_found' ? 404 : (bad.has(uploaded.error) ? 400 : 502);
        return sendJson(res, status, { error: uploaded.error || 'upload_failed', detail: uploaded.detail || 'upload failed' });
      }
      return sendJson(res, 200, uploaded);
    }
    if (method === 'GET'   && sub === '/logs')             return sendJson(res, 200, { logs: '', truncated: false });
    if (method === 'GET'   && sub === '/output') {
      const id = agentMatch[1];
      const lines = Math.max(0, parseInt(url.searchParams.get('lines') || '50', 10) || 50);
      const format = (url.searchParams.get('format') === 'ansi') ? 'ansi' : 'plain';
      const resolved = _contextForAgent(id);
      if (resolved.error) {
        return sendJson(res, 502, {
          error:  resolved.error,
          detail: `Output unavailable: ${resolved.error}`,
        });
      }
      let exec = await _execCamcOnContext(resolved.ctx, _captureArgs(id, lines, format));
      if (!exec.ok && format === 'ansi' && _isUnsupportedCaptureFormat(exec)) {
        exec = await _execCamcOnContext(resolved.ctx, _captureArgs(id, lines, 'plain', false));
      }
      if (!exec.ok) {
        pushLog('warn', `output ${id} via ${resolved.ctx.name} failed: ${exec.error}`);
        return sendJson(res, 502, {
          error:  exec.error,
          detail: `Output unavailable: ${exec.detail || exec.error}`,
        });
      }
      const output = exec.stdout;
      const hash = crypto.createHash('md5').update(output).digest('hex').slice(0, 12);
      const lineCount = output ? output.split('\n').length : 0;
      return sendJson(res, 200, { output, hash, lines: lineCount });
    }
    if (method === 'GET'   && sub === '/fulloutput') {
      const id = agentMatch[1];
      const format = (url.searchParams.get('format') === 'ansi') ? 'ansi' : 'plain';
      const resolved = _contextForAgent(id);
      if (resolved.error) {
        return sendJson(res, 502, {
          error:  resolved.error,
          detail: `Output unavailable: ${resolved.error}`,
        });
      }
      // lines=0 → full scrollback per `camc capture` default.
      let exec = await _execCamcOnContext(resolved.ctx, _captureArgs(id, 0, format));
      if (!exec.ok && format === 'ansi' && _isUnsupportedCaptureFormat(exec)) {
        exec = await _execCamcOnContext(resolved.ctx, _captureArgs(id, 0, 'plain', false));
      }
      if (!exec.ok) {
        pushLog('warn', `fulloutput ${id} via ${resolved.ctx.name} failed: ${exec.error}`);
        return sendJson(res, 502, {
          error:  exec.error,
          detail: `Output unavailable: ${exec.detail || exec.error}`,
        });
      }
      return sendJson(res, 200, { output: exec.stdout, offset: 0 });
    }
    if (method === 'GET' && sub === '/workspace/files') {
      const subpath = url.searchParams.get('path') || '';
      const out = await _browseAgentList(agentMatch[1], subpath);
      return sendJson(res, out.httpStatus, out.body);
    }
    if (method === 'GET' && sub === '/workspace/files/read') {
      const subpath = url.searchParams.get('path') || '';
      const out = await _browseAgentRead(agentMatch[1], subpath);
      return sendJson(res, out.httpStatus, out.body);
    }
    return send404(res);
  }

  return send404(res);
}

/* ─────────────── Port discovery ─────────────── */

function portInUse(port) {
  return new Promise((resolve) => {
    const probe = http.createServer();
    probe.once('error', () => resolve(true));
    probe.once('listening', () => {
      probe.close(() => resolve(false));
    });
    probe.listen({ host: '127.0.0.1', port });
  });
}

async function pickPort() {
  for (let p = DEFAULT_PORT; p < DEFAULT_PORT + PORT_SCAN_RANGE; p++) {
    // eslint-disable-next-line no-await-in-loop
    if (!(await portInUse(p))) return p;
  }
  return null;
}

/* ─────────────── Lifecycle ─────────────── */

async function start({ dataDir } = {}) {
  if (state.server) {
    return {
      ok:        true,
      apiUrl:    `http://127.0.0.1:${state.port}`,
      apiToken:  state.token,
      reused:    true,
      state:     publicState(),
    };
  }

  if (dataDir && !state.store) loadStore(dataDir);
  if (!state.store) state.store = _emptyStore();

  const port = await pickPort();
  if (port == null) {
    state.lastError = `No free loopback port in ${DEFAULT_PORT}..${DEFAULT_PORT + PORT_SCAN_RANGE - 1}.`;
    pushLog('error', state.lastError);
    return { ok: false, error: state.lastError, state: publicState() };
  }

  state.token = genToken();
  state.port  = port;

  const srv = http.createServer(async (req, res) => {
    try {
      await handle(req, res);
    } catch (e) {
      pushLog('error', `route error: ${e && e.message}`);
      try { sendJson(res, 500, { error: 'internal_error' }); } catch {}
    }
  });

  srv.on('clientError', (err, sock) => {
    pushLog('warn', `clientError: ${err && err.message}`);
    try { sock.destroy(); } catch {}
  });

  await new Promise((resolve, reject) => {
    srv.once('error', reject);
    srv.listen({ host: '127.0.0.1', port }, () => resolve());
  }).catch((e) => {
    state.lastError = `listen failed on 127.0.0.1:${port}: ${e && e.message}`;
    pushLog('error', state.lastError);
  });

  if (!srv.listening) {
    state.token = null;
    state.port  = null;
    return { ok: false, error: state.lastError || 'listen failed', state: publicState() };
  }

  state.server    = srv;
  state.startedAt = Date.now();
  state.owned     = true;
  state.lastError = null;
  pushLog('info', `embedded Hub listening on 127.0.0.1:${port}`);

  return {
    ok:       true,
    apiUrl:   `http://127.0.0.1:${port}`,
    apiToken: state.token,
    state:    publicState(),
  };
}

async function stop() {
  if (!state.server) {
    return { ok: true, state: publicState() };
  }
  await new Promise((resolve) => {
    try { state.server.close(() => resolve()); }
    catch { resolve(); }
  });
  state.server    = null;
  state.startedAt = 0;
  state.owned     = false;
  // Token is intentionally cleared on Stop so the renderer cannot
  // reuse a stale credential against a different process listening
  // on the same port later.
  state.token     = null;
  pushLog('info', 'embedded Hub stopped');
  return { ok: true, state: publicState() };
}

async function restart({ dataDir } = {}) {
  await stop();
  return start({ dataDir });
}

async function check({ dataDir } = {}) {
  if (dataDir && !state.store) loadStore(dataDir);

  let summary;
  let probedPort;
  let portState;

  if (state.server) {
    // We're already up. Report the port we own.
    probedPort = state.port;
    portState  = 'embedded-hub';
    summary    = 'running';
  } else {
    // Mirror what start() would actually do: scan the candidate range
    // and pick the first free loopback port. Reporting 'port-conflict'
    // only when ALL candidates are taken keeps the UI Start button
    // enabled when the default 8420 is busy but 8421+ is free, which
    // is the behavior start() would take anyway.
    const defaultBusy = await portInUse(DEFAULT_PORT);
    const startable   = await pickPort();
    if (startable == null) {
      probedPort = DEFAULT_PORT;
      portState  = 'other';
      summary    = 'port-conflict';
    } else {
      probedPort = startable;
      portState  = defaultBusy ? 'alternate-free' : 'free';
      summary    = 'stopped';
    }
  }

  return {
    platform:       process.platform,
    runtime:        'embedded',
    apiPort:        probedPort,
    apiPortStatus:  { state: portState },
    summary,
    state:          publicState(),
    lastError:      state.lastError || null,
  };
}

function publicState() {
  return {
    server: {
      owned:            state.owned,
      pid:              state.server ? process.pid : null,
      port:             state.port,
      startedAt:        state.startedAt || null,
      tokenFingerprint: tokenFingerprint(state.token),
    },
  };
}

function getLogs() {
  // Return the same shape the renderer's diag panel expects: { server: [...] }.
  return { server: state.logs.slice() };
}

function getProfile() {
  return {
    apiUrl:  state.port ? `http://127.0.0.1:${state.port}` : null,
    state:   publicState(),
  };
}

/* ─────────────── Exports ─────────────── */

/**
 * Build the SSH connect options the main process needs to attach a
 * terminal channel to <agentId>. Resolves the agent's owning context,
 * pulls the (decrypted) password/passphrase out of the credential
 * store if remembered, and returns a plain object suitable for
 * sshTransport.openTerminalChannel(). Secrets stay in main-process
 * memory — this helper is not exposed via IPC or preload.
 *
 * Returns one of:
 *   { ok: true,  agent, ctx, opts }
 *   { ok: false, error, detail }
 */
function _machineMatchesAgent(ctx, agent) {
  const m = (ctx && ctx.machine) || {};
  return (m.type || 'local') === (agent.machine_type || agent.transport_type || 'local')
    && (m.host || '') === (agent.machine_host || '')
    && (m.user || '') === (agent.machine_user || '')
    && String(m.port == null ? '' : m.port) === String(agent.machine_port == null ? '' : agent.machine_port);
}

function _attachContextForAgent(agent, fallbackCtx) {
  const ctxs = Array.isArray(state.store && state.store.contexts) ? state.store.contexts : [];
  const byMachine = ctxs.find(ctx => _machineMatchesAgent(ctx, agent));
  if (byMachine) return byMachine;
  const byName = agent && agent.context_name ? ctxs.find(c => c && c.name === agent.context_name) : null;
  return byName || fallbackCtx || null;
}

async function getAttachConnectOpts(agentId) {
  const resolved = _contextForAgent(agentId);
  if (resolved.error) {
    return { ok: false, error: resolved.error, detail: `agent ${agentId}: ${resolved.error}` };
  }
  const agent = resolved.agent || {};
  const ctx = _attachContextForAgent(agent, resolved.ctx);
  if (!ctx) return { ok: false, error: 'context_not_found', detail: `agent ${agentId}: context_not_found` };

  // Match `cam attach`: the live agent machine fields are the source of
  // truth for where the agent actually runs. The context supplies auth
  // metadata/credentials, but stale context host/user/port must not redirect
  // an attach to the wrong endpoint. Do not pre-filter by agent status here;
  // `camc attach` has the authoritative tmux-session check and returns the
  // useful stale-session error when needed.
  const built = _sshBaseOptsForContext(ctx, 60000);
  if (built.error) return { ok: false, error: built.error, detail: built.detail };
  const opts = { ...built.opts };
  if ((agent.machine_type || agent.transport_type || 'ssh') !== 'ssh') {
    return { ok: false, error: 'not_ssh', detail: `agent ${agentId}: terminal attach requires an SSH-backed agent` };
  }
  if (agent.machine_host) opts.host = agent.machine_host;
  if (agent.machine_user) opts.user = agent.machine_user;
  if (agent.machine_port != null && agent.machine_port !== '') opts.port = agent.machine_port;

  const ready = await _ensureRemoteCamc(opts);
  if (!ready.ok) {
    return { ok: false, error: ready.error || 'remote_camc_unavailable', detail: ready.detail || 'failed to prepare ~/.cam/camc on remote host' };
  }
  return {
    ok: true,
    agent,
    ctx,
    opts,
    command: `${REMOTE_CAMC} attach ${_shellQuote(agent.id || agentId)}`,
  };
}

module.exports = {
  configure,
  start,
  stop,
  restart,
  check,
  getLogs,
  getProfile,
  getAttachConnectOpts,
};
